/**
 * Phase-2 Arabic UI preview copy.
 *
 * This is not wired into AppLanguage or release selection. It gives reviewers a
 * typed, testable first Arabic app-UI slice while `ar` remains unavailable in
 * lib/i18n/locales.ts and blocked in docs/localization/readiness.json.
 */
export const arUiPreview = {
  locale: 'ar',
  status: 'preview_only_release_blocked',
  sourceStyleGuide: 'docs/localization/sample-corpus/ar/style-guide.md',
  sourcePhrasebook: 'locales/ar/phrasebook.md',
  settings: {
    title: 'الإعدادات',
    subtitle: 'إدارة لغة الأسئلة والصوت والمظهر والهدف اليومي.',
    backToProfile: '← الرجوع إلى الملف الشخصي',
    backToProfileAccessibilityLabel: 'الرجوع إلى الملف الشخصي',
    questionLanguageTitle: 'لغة الأسئلة',
    languageAccessibilityLabelTemplate: 'غيّر لغة الأسئلة إلى: {label}',
    languageOptions: {
      sv: 'السويدية',
      en: 'دعم باللغة الإنجليزية',
    },
    audioTitle: 'الصوت',
    audioEnabledLabel: 'الصوت مفعّل',
    audioDisabledLabel: 'الصوت متوقف',
    enableAudioAccessibilityLabel: 'فعّل الصوت',
    disableAudioAccessibilityLabel: 'أوقف الصوت',
    themeModeTitle: 'المظهر',
    themeSystemLabel: 'اتبع إعداد الجهاز',
    themeLightLabel: 'فاتح',
    themeDarkLabel: 'داكن',
    themeModeSummaryTemplate: 'المظهر الحالي: {label}',
    setThemeModeAccessibilityLabelTemplate: 'اختر المظهر: {label}',
    dailyGoalTitle: 'الهدف اليومي',
    dailyGoalSummaryTemplate: '{answerCount} سؤالًا في اليوم',
    dailyGoalPresetLabels: {
      5: 'هادئ',
      10: 'منتظم',
      20: 'مكثف',
      40: 'كبير',
    },
    setDailyGoalAccessibilityLabelTemplate: 'حدّد الهدف اليومي: {goal} سؤالًا',
    importTitle: 'استيراد بيانات الدراسة',
    importSectionSubtitle:
      'الصق ملف JSON الذي صُدّر من هذا التطبيق. ستظهر لك خلاصة قبل حفظ أي بيانات.',
    importPurchasesNote:
      'لا تُستورد المشتريات أو الإيصالات أو بيانات متجر التطبيق. استعد المشتريات من متجر التطبيق.',
    importPasteLabel: 'الصق ملف JSON المصدّر',
    importPastePlaceholder: 'الصق بيانات التصدير هنا',
    importPreview: 'راجع الاستيراد',
    importPreviewAccessibilityLabel: 'راجع استيراد بيانات الدراسة على هذا الجهاز',
    importReset: 'امسح حقل الاستيراد',
    confirmImport: 'أكّد الاستيراد',
    confirmImportAccessibilityLabel: 'أكّد استيراد بيانات الدراسة على هذا الجهاز',
    importSuccess: 'اكتمل الاستيراد.',
    importSummaryTitle: 'خلاصة قبل الاستيراد',
    importSummaryTemplates: {
      completedQuestions: '{count} سؤالًا لها تقدم محفوظ',
      bookmarks: '{count} سؤالًا محددًا للمراجعة',
      wrongAnswers: '{count} سجلًا لإجابات غير صحيحة',
      mockExams: '{count} سجلًا لاختبار تجريبي',
      fsrsCards: '{count} بطاقة مراجعة FSRS',
      fsrsDays: '{count} يومًا من مراجعة FSRS',
      settings: '{count} إعدادًا',
      streakFreeze: 'تم تضمين أيام الدراسة المتتالية وحمايتها',
    },
    importErrors: {
      emptyInput: 'الصق JSON قبل المراجعة.',
      invalidJson: 'لا يمكن قراءة ملف JSON هذا.',
      invalidSchema: 'بنية الاستيراد غير صحيحة أو تحتوي على حقول غير معروفة.',
      unsupportedVersion: 'إصدار الاستيراد هذا غير مدعوم حاليًا.',
      purchaseFieldsRejected:
        'يتضمن الاستيراد حقولًا مرتبطة بالمشتريات أو الإيصالات أو متجر التطبيق. احذفها ثم استعد المشتريات من متجر التطبيق.',
      noSupportedStudyData: 'لا يتضمن الاستيراد بيانات دراسة مدعومة.',
    },
  },
  languagePicker: {
    title: 'اختر لغة الأسئلة',
    currentLanguageLabelTemplate: 'اللغة الحالية: {label}',
    availableBadge: 'متاحة',
    unavailableBadge: 'قيد الإعداد',
    comingSoonTitle: 'هذا الإصدار قيد الإعداد.',
    comingSoonBody:
      'تخضع النصوص العربية للمراجعة قبل إتاحتها. إلى ذلك الحين، يبقى التطبيق متاحًا بالسويدية والإنجليزية.',
    blockedAccessibilityLabelTemplate: '{label}: إصدار اللغة قيد الإعداد',
  },
  studyEntryPoints: {
    home: {
      eyebrow: 'خطة الدراسة',
      title: 'تعلّم معلومات المجتمع في السويد خطوة بخطوة',
      subtitle:
        'تدريب يومي واختبار تجريبي ومراجعة للأخطاء وشروح قصيرة بالاستناد إلى مادة UHR المرجعية.',
      startPractice: 'ابدأ التدريب',
      startPracticeAccessibilityLabel: 'ابدأ التدريب المقترح',
      browseChapters: 'تصفح الأقسام',
      browseChaptersAccessibilityLabel: 'تصفح كل الأقسام',
      dailyPracticeTitle: 'تدريب يومي',
      dailyPracticeTextTemplate: 'أجبت اليوم عن {completed} من {goal} سؤالًا.',
      readinessTitle: 'مؤشر الاستعداد',
      readinessSparseNote:
        'هذا مجرد دعم دراسي بناءً على إجاباتك الحالية. يصبح أكثر فائدة عندما تجيب عن أسئلة أكثر.',
      feedbackTitle: 'احتفظ بما يحتاج إلى مراجعة',
      feedbackText: 'تبقى الأسئلة المحددة والإجابات غير الصحيحة في مكان واحد مع الشرح والمصدر.',
    },
    practice: {
      badge: 'تدريب لمدة 5 دقائق',
      questionTitleTemplate: 'السؤال {questionNumber}',
      subtitle: 'أجب، ثم راجع الملاحظات واقرأ الإحالة إلى مادة UHR المرجعية.',
      completedQuestionsTemplate: 'الأسئلة المنجزة: {count}',
      emptyTitle: 'لا توجد أسئلة تدريبية بعد.',
      nextQuestion: 'السؤال التالي',
      nextQuestionAccessibilityLabel: 'انتقل إلى السؤال التدريبي التالي',
      tryAgain: 'حاول مرة أخرى',
      tryAgainAccessibilityLabel: 'حاول الإجابة عن هذا السؤال التدريبي مرة أخرى',
      bookmark: 'حدّد للمراجعة',
      bookmarked: 'محدد للمراجعة',
      bookmarkAccessibilityLabels: {
        add: 'حدّد هذا السؤال للمراجعة',
        remove: 'أزل تحديد هذا السؤال للمراجعة',
      },
      sourceDetailsShow: 'عن المصادر',
      sourceDetailsHide: 'إخفاء تفاصيل المصادر',
      uhrSourceLabel: 'مصدر UHR',
    },
    feedback: {
      correct: 'إجابة صحيحة.',
      incorrect: 'لم تكن الإجابة صحيحة هذه المرة.',
      correctAnswerLabel: 'الإجابة الصحيحة',
      yourAnswerLabel: 'إجابتك',
      explanationTitle: 'شرح الإجابة',
      sourceCitationLabel: 'مادة مرجعية',
      encouragement: 'لا بأس، يساعدك الشرح على تذكّر الفكرة.',
    },
    mockExam: {
      title: 'اختبار تجريبي',
      subtitle:
        'تدرّب بطريقة محددة بالوقت لمعرفة الموضوعات التي تحتاج إلى مراجعة. ليس اختبارًا رسميًا.',
      setupTitle: 'حضّر الاختبار التجريبي',
      start: 'ابدأ الاختبار التجريبي',
      startAccessibilityLabel: 'ابدأ الاختبار التجريبي المخصص للدراسة',
      questionProgressTemplate: 'السؤال {current} من {total}',
      timeRemainingTemplate: 'الوقت المتبقي: {minutes} دقيقة',
      submit: 'أنهِ وشاهد النتيجة',
      resultTitle: 'نتيجة الاختبار التجريبي',
      resultSummaryTemplate: '{correct} إجابة صحيحة من {total} سؤالًا',
      reviewAnswers: 'راجع الإجابات والشروح',
      localPracticeNote: 'هذه النتيجة تساعدك على الدراسة داخل التطبيق ولا يتنبأ بنتيجة رسمية.',
    },
    mistakes: {
      title: 'راجع الأخطاء',
      subtitle: 'ارجع إلى الأسئلة التي لم تكن إجابتها صحيحة واقرأ الإجابة الصحيحة والشرح والمصدر.',
      emptyTitle: 'لا توجد أخطاء بعد',
      emptyBody: 'عندما لا تكون إجابة سؤال تدريبي صحيحة، سيظهر هنا للمراجعة بهدوء.',
      savedForReview: 'حُفظ للمراجعة',
      wrongAnswersTemplate: 'إجابات غير صحيحة: {count}',
      latestWrongAnswer: 'آخر إجابة غير صحيحة',
      reviewQuestion: 'راجع هذا السؤال',
      clearReviewed: 'أزل بعد الفهم',
    },
    dashboard: {
      eyebrow: 'التقدم',
      title: 'تقدمك',
      subtitle: 'اعرف ما أنجزته والموضوعات التي تستحق الرجوع إليها.',
      completedQuestions: 'أسئلة منجزة',
      correctAnswers: 'إجابات صحيحة',
      currentStreak: 'أيام متتالية من التدريب',
      reviewQueue: 'أسئلة تحتاج إلى مراجعة',
      sparseDataNote: 'تصبح هذه الخلاصة أكثر فائدة بعد إجابات أكثر. لا تعاملها كتقييم رسمي.',
    },
    learning: {
      title: 'مسار التعلم',
      subtitle: 'تقدم حسب الموضوعات، واقرأ شروحًا قصيرة، وتدرّب بأسئلة لها مصادر.',
      chapterCardQuestionCountTemplate: '{count} سؤالًا',
      chapterProgressTemplate: 'أُنجز {completed} من {total}',
      startChapter: 'ابدأ هذا القسم',
      reviewChapter: 'راجع هذا القسم',
      continueLearning: 'تابع التعلم',
      lockedReleaseNote: 'هذا الإصدار اللغوي قيد الإعداد ولن يُفتح قبل اكتمال كل المراجعات.',
    },
  },
  complianceAndMonetization: {
    complianceLinks: {
      title: 'معلومات قانونية ومصادر',
      openLabelTemplate: 'افتح: {label}',
      links: {
        aboutTheTest: 'عن الاختبار',
        disclaimer: 'إخلاء مسؤولية',
        privacy: 'الخصوصية',
        terms: 'الشروط',
        sources: 'مصادر التعلم',
        support: 'الدعم',
      },
    },
    legalPage: {
      defaultBackLabel: '← الرجوع إلى الملف الشخصي',
      defaultBackAccessibilityLabel: 'الرجوع إلى الملف الشخصي',
      externalLinkAccessibilityTemplate: 'افتح صفحة خارجية: {label}',
    },
    privacy: {
      title: 'سياسة الخصوصية',
      noAccountRequired: {
        title: 'لا يلزم حساب',
        body: 'لا يطلب هذا التطبيق حسابًا أو بريدًا إلكترونيًا أو هاتفًا أو ملفًا شخصيًا. يمكنك استخدام أقسام الدراسة دون تسجيل.',
      },
      localProgressStorage: {
        title: 'يُحفظ تقدمك في الدراسة على هذا الجهاز فقط',
        body: 'يُحفظ التقدم والإعدادات والأسئلة المحددة والإجابات غير الصحيحة و XP وأيام الدراسة المتتالية واختيار الصوت على هذا الجهاز حتى يتذكر التطبيق أين توقفت.',
      },
      adsAndPurchases: {
        title: 'الإعلانات والمشتريات',
        body: 'قد تعرض النسخة المجانية إعلانات في صفحات الدراسة. لا توجد إعلانات في صفحات الاختبار التجريبي المحدد بالوقت. إزالة الإعلانات عملية شراء لمرة واحدة ويمكن استعادتها من متجر التطبيق.',
      },
      dataBoundary: {
        title: 'لا ترسل معلومات حساسة',
        body: 'لا ترسل اسمك أو رقم الهوية أو تفاصيل ملف الهجرة أو وثائق رسمية في رسائل الدعم. لا يحتاج التطبيق إلى هذه المعلومات لمساعدتك في الدراسة.',
      },
    },
    monetization: {
      removeAdsTitle: 'إزالة الإعلانات',
      removeAdsActiveTitle: 'الدراسة دون إعلانات مفعّلة',
      removeAdsBodyTemplate:
        'قد تحتوي صفحات الدراسة المجانية على إعلانات. تدفع {price} مرة واحدة لإزالة الإعلانات من صفحات الدراسة؛ الاختبار التجريبي لا يحتوي على إعلانات.',
      pricingPitchTemplate: 'دفعة واحدة بقيمة {price} تزيل الإعلانات. هذا ليس اشتراكًا شهريًا.',
      buyLabelTemplate: 'اشترِ مقابل {price}',
      restoreLabel: 'استعد شراءً سابقًا',
      statusMessages: {
        idle: 'إذا كنت قد اشتريت سابقًا، يمكنك الاستعادة هنا.',
        pending: 'ننتظر تأكيد متجر التطبيق.',
        purchased: 'تم إيقاف الإعلانات على هذا الجهاز.',
        restored: 'تمت استعادة الشراء وإيقاف الإعلانات.',
        error: 'الشراء غير متاح الآن. حاول لاحقًا.',
      },
    },
  },
  remainingHighFrequencyRoutes: {
    onboarding: {
      eyebrow: 'مرحبًا بك',
      title: 'استعد بهدوء لمعرفة المجتمع في السويد',
      subtitle: 'أداة دراسة مستقلة: تدريب يومي، واختبار تجريبي، ومراجعة للإجابات غير الصحيحة.',
      chooseLanguage: 'اختر لغة الأسئلة',
      setGoal: 'حدّد الهدف اليومي',
      startLearning: 'ابدأ التعلم',
      privacyNote: 'يُحفظ تقدم الدراسة على هذا الجهاز فقط. لا يلزم حساب.',
    },
    aboutTheTest: {
      eyebrow: 'عن الاختبار',
      title: 'ما الذي يساعدك هذا التطبيق على تدريبه',
      body: 'يساعدك التطبيق على مراجعة الديمقراطية والحقوق والواجبات والمؤسسات في السويد. ويُبقي أسماء المؤسسات السويدية، مثل البرلمان السويدي (الريكسداغ)، بدل استبدالها بمؤسسات من دولة أخرى.',
      independenceTitle: 'ليس اختبارًا رسميًا',
      independenceBody:
        'هذا التطبيق أداة دراسة مستقلة. لا يمثل UHR أو مصلحة الهجرة السويدية أو أي سلطة حكومية أخرى، ولا يقدم وعدًا بشأن أي قرار رسمي.',
      sourceBoundary:
        'أُعدت مواد الدراسة بالاستناد إلى مادة UHR المرجعية ومعلومات عامة. تحقق دائمًا من المعلومات الأحدث لدى الجهة المختصة.',
    },
    support: {
      title: 'الدعم والملاحظات',
      subtitle:
        'اكتب إلينا إذا كان النص غير واضح أو كان مصدر يحتاج إلى مراجعة أو كان شيء ما لا يعمل.',
      feedbackPrompt: 'صف المشكلة أو الاقتراح',
      privacyReminder: 'لا ترسل بيانات شخصية أو وثائق. يكفي وصف الشاشة أو السؤال أو جزء النص.',
      sendFeedback: 'أرسل الملاحظات',
    },
    sources: {
      title: 'مصادر التعلم',
      subtitle:
        'تحقق من المادة التي يستند إليها السؤال أو الشرح. لا يعني وسم المصدر أن هذا التطبيق معتمد من تلك الجهة.',
      uhrLabel: 'مادة UHR المرجعية',
      publicInfoLabel: 'معلومات عامة من جهات رسمية',
      openSource: 'افتح المصدر',
    },
    search: {
      title: 'ابحث عن المفاهيم والأقسام',
      placeholder: 'اكتب موضوعًا أو مؤسسة أو كلمة مفتاحية',
      emptyTitle: 'لا توجد نتائج',
      emptyBody: 'جرّب عبارة أقصر، مثل «Riksdag» أو «البلدية» أو «الحقوق».',
      resultTypeLabels: {
        chapter: 'قسم',
        question: 'سؤال',
        glossary: 'مفهوم',
      },
    },
  },
};
