/**
 * Phase-2 Tigrinya UI preview copy.
 *
 * This is not wired into AppLanguage or release selection. It gives reviewers a
 * typed, testable first Tigrinya app-UI slice while `ti` remains unavailable in
 * lib/i18n/locales.ts and blocked in docs/localization/readiness.json.
 */
export const tiUiPreview = {
  locale: 'ti',
  status: 'preview_only_release_blocked',
  sourceStyleGuide: 'docs/localization/sample-corpus/ti/style-guide.md',
  sourcePhrasebook: 'locales/ti/phrasebook.md',
  settings: {
    title: 'ቅጥዕታት',
    subtitle: 'ቋንቋ ሕቶታት፣ ድምጺ፣ ትርኢትን ዕላማ መዓልታዊን ኣመሓድር።',
    backToProfile: '← ናብ ፕሮፋይል ተመለስ',
    backToProfileAccessibilityLabel: 'ናብ ፕሮፋይል ተመለስ',
    questionLanguageTitle: 'ቋንቋ ሕቶታት',
    languageAccessibilityLabelTemplate: 'ቋንቋ ሕቶታት ናብ {label} ቀይር',
    languageOptions: {
      sv: 'ሽወደንኛ',
      en: 'ደገፍ ብእንግሊዝኛ',
    },
    audioTitle: 'ድምጺ',
    audioEnabledLabel: 'ድምጺ ተኸፊቱ ኣሎ',
    audioDisabledLabel: 'ድምጺ ተዓጽዩ ኣሎ',
    enableAudioAccessibilityLabel: 'ድምጺ ክፈት',
    disableAudioAccessibilityLabel: 'ድምጺ ዕጾ',
    themeModeTitle: 'ትርኢት',
    themeSystemLabel: 'ቅጥዒ መሳርሒ ተኸተል',
    themeLightLabel: 'ብርሃን',
    themeDarkLabel: 'ጸሊም',
    themeModeSummaryTemplate: 'ናይ ሕጂ ትርኢት፦ {label}',
    setThemeModeAccessibilityLabelTemplate: 'ትርኢት ምረጽ፦ {label}',
    dailyGoalTitle: 'ዕላማ መዓልታዊ',
    dailyGoalSummaryTemplate: 'ኣብ መዓልቲ {answerCount} ሕቶታት',
    dailyGoalPresetLabels: {
      5: 'ህድእ',
      10: 'ቀጻሊ',
      20: 'ዝተጠናኸረ',
      40: 'ብዙሕ',
    },
    setDailyGoalAccessibilityLabelTemplate: 'ዕላማ መዓልታዊ ኣቐምጥ፦ {goal} ሕቶታት',
    importTitle: 'ዳታ ምምሃር ኣእቱ',
    importSectionSubtitle: 'ካብዚ መተግበሪ ዝተወጽአ JSON ለጥፍ። ዝኾነ ዳታ ቅድሚ ምጽሓፉ ሓጺር ጽማቝ ክትርኢ ኢኻ።',
    importPurchasesNote: 'ዕድጊታት፣ ቅብሊታትን ዳታ ድኳን መተግበሪን ኣይኣቱን። ዕድጊታት ካብ ድኳን መተግበሪ መልስ።',
    importPasteLabel: 'JSON ምውጻእ ለጥፍ',
    importPastePlaceholder: 'ምውጻእ ኣብዚ ለጥፍ',
    importPreview: 'ምእታው መርምር',
    importPreviewAccessibilityLabel: 'ምእታው ዳታ ምምሃር ኣብዚ መሳርሒ መርምር',
    importReset: 'ቦታ ምእታው ኣጽርይ',
    confirmImport: 'ምእታው ኣረጋግጽ',
    confirmImportAccessibilityLabel: 'ምእታው ዳታ ምምሃር ኣብዚ መሳርሒ ኣረጋግጽ',
    importSuccess: 'ምእታው ተዛዚሙ።',
    importSummaryTitle: 'ቅድሚ ምእታው ጽማቝ',
    importSummaryTemplates: {
      completedQuestions: '{count} ሕቶታት ዝተቐመጠ ምዕባለ ኣለዎም',
      bookmarks: '{count} ሕቶታት ንምምርማር ተሓዚኦም',
      wrongAnswers: '{count} መዝገባት ዘይትኽክለኛ መልሲ',
      mockExams: '{count} መዝገባት ፈተና ልምምድ',
      fsrsCards: '{count} ካርድታት ምምርማር FSRS',
      fsrsDays: '{count} መዓልታት ምምርማር FSRS',
      settings: '{count} ቅጥዕታት',
      streakFreeze: 'ተኸታታሊ መዓልታት ልምምድን መከላኸሊኦምን ተኻቲቶም ኣለዉ',
    },
    importErrors: {
      emptyInput: 'ቅድሚ ምምርማር JSON ለጥፍ።',
      invalidJson: 'እዚ JSON ክንበብ ኣይክእልን።',
      invalidSchema: 'ናይ ምእታው ቅርጺ ትኽክል ኣይኮነን ወይ ዘይፍለጡ መዳያት ኣለዎ።',
      unsupportedVersion: 'እዚ ናይ ምእታው ስሪት ኣብዚ ግዜ ኣይድገፍን።',
      purchaseFieldsRejected:
        'ምእታው ምስ ዕድጊ፣ ቅብሊት ወይ ድኳን መተግበሪ ዝተኣሳሰሩ መዳያት ኣለዎ። ኣልግሶም፣ ዕድጊታት ድማ ካብ ድኳን መተግበሪ መልስ።',
      noSupportedStudyData: 'ምእታው ዝድገፍ ዳታ ምምሃር የብሉን።',
    },
  },
  languagePicker: {
    title: 'ቋንቋ ሕቶታት ምረጽ',
    currentLanguageLabelTemplate: 'ናይ ሕጂ ቋንቋ፦ {label}',
    availableBadge: 'ይርከብ',
    unavailableBadge: 'ይዳሎ ኣሎ',
    comingSoonTitle: 'እዚ ቋንቋ ገና ይዳሎ ኣሎ።',
    comingSoonBody: 'ጽሑፍ ትግርኛ ቅድሚ ምኽፋቱ ይምርመር ኣሎ። ክሳብ ሽዑ መተግበሪ ብሽወደንኛን እንግሊዝኛን ይርከብ።',
    blockedAccessibilityLabelTemplate: '{label}፦ እዚ ቋንቋ ገና ይዳሎ ኣሎ',
  },
  studyEntryPoints: {
    home: {
      eyebrow: 'መደብ ምምሃር',
      title: 'ብዛዕባ ሕብረተሰብ ኣብ ሽወደን በብደረጃ ተማሃር',
      subtitle: 'መዓልታዊ ልምምድ፣ ፈተና ልምምድ፣ ምምርማር ጌጋታትን ሓጺር መብርሂ ኣብ መወከሲ ጽሑፍ UHR ተመርኲሱ።',
      startPractice: 'ልምምድ ጀምር',
      startPracticeAccessibilityLabel: 'ዝተመከረ ልምምድ ጀምር',
      browseChapters: 'ክፍልታት ርአ',
      browseChaptersAccessibilityLabel: 'ኵሉ ክፍልታት ርአ',
      dailyPracticeTitle: 'መዓልታዊ ልምምድ',
      dailyPracticeTextTemplate: 'ሎሚ {completed} ካብ {goal} ሕቶታት መሊስካ።',
      readinessTitle: 'ምልክት ድልውነት',
      readinessSparseNote: 'እዚ ብመልስታትካ ክሳብ ሕጂ ዝተመርኰሰ ደገፍ ምምሃር ጥራይ እዩ። ብዙሕ ሕቶታት ምስ መለስካ ዝያዳ ይጠቅም።',
      feedbackTitle: 'ንምምርማር ዘድሊ ኣቐምጥ',
      feedbackText: 'ዝተሓዝኡ ሕቶታትን ዘይትኽክለኛ መልስታትን ምስ መብርሂን ምንጪን ኣብ ሓደ ቦታ ይቕመጡ።',
    },
    practice: {
      badge: 'ልምምድ 5 ደቓይቕ',
      questionTitleTemplate: 'ሕቶ {questionNumber}',
      subtitle: 'መልሲ ሃብ፣ ርእይቶ ርአ፣ ድሕሪኡ መወከሲ ጽሑፍ UHR ኣንብብ።',
      completedQuestionsTemplate: 'ዝተዛዘሙ ሕቶታት፦ {count}',
      emptyTitle: 'ገና ሕቶ ልምምድ የለን።',
      nextQuestion: 'ዝቕጽል ሕቶ',
      nextQuestionAccessibilityLabel: 'ናብ ዝቕጽል ሕቶ ልምምድ ኪድ',
      tryAgain: 'እንደገና ፈትን',
      tryAgainAccessibilityLabel: 'እዚ ሕቶ ልምምድ እንደገና ፈትን',
      bookmark: 'ንምምርማር ሓዝ',
      bookmarked: 'ንምምርማር ተሓዚኡ',
      bookmarkAccessibilityLabels: {
        add: 'እዚ ሕቶ ንምምርማር ሓዝ',
        remove: 'እዚ ሕቶ ካብ ምምርማር ኣልግስ',
      },
      sourceDetailsShow: 'ብዛዕባ ምንጭታት',
      sourceDetailsHide: 'ዝርዝር ምንጭታት ሕባእ',
      uhrSourceLabel: 'ምንጪ UHR',
    },
    feedback: {
      correct: 'መልስኻ ትኽክል እዩ።',
      incorrect: 'ኣብዚ ግዜ መልስኻ ትኽክል ኣይነበረን።',
      correctAnswerLabel: 'ትኽክለኛ መልሲ',
      yourAnswerLabel: 'መልስኻ',
      explanationTitle: 'መብርሂ መልሲ',
      sourceCitationLabel: 'መወከሲ ጽሑፍ',
      encouragement: 'ጸገም የለን፤ እዚ ሓሳብ ብልምምድ ይጸንዕ።',
    },
    mockExam: {
      title: 'ፈተና ልምምድ',
      subtitle: 'ብግዜ ዝተወሰነ ቅርጺ ተለማመድ፣ ኣየኖት ርእስታት ገና ምምርማር ከም ዘድልዮም ርአ። ናይ መንግስቲ ፈተና ኣይኮነን።',
      setupTitle: 'ፈተና ልምምድ ኣዳሉ',
      start: 'ፈተና ልምምድ ጀምር',
      startAccessibilityLabel: 'ንምምሃር ፈተና ልምምድ ጀምር',
      questionProgressTemplate: 'ሕቶ {current} ካብ {total}',
      timeRemainingTemplate: 'ዝተረፈ ግዜ፦ {minutes} ደቓይቕ',
      submit: 'ዛዝም እሞ ውጽኢት ርአ',
      resultTitle: 'ውጽኢት ፈተና ልምምድ',
      resultSummaryTemplate: '{correct} ትኽክለኛ መልስታት ካብ {total} ሕቶታት',
      reviewAnswers: 'መልስታትን መብርሂታትን መርምር',
      localPracticeNote: 'እዚ ውጽኢት ኣብዚ መተግበሪ ምምሃርካ ይሕግዝ፣ ናይ መንግስቲ ውጽኢት ኣይግምትን።',
    },
    mistakes: {
      title: 'ጌጋታትካ መርምር',
      subtitle: 'ናብ ዘይትኽክለኛ መልሲ ዝነበሮም ሕቶታት ተመለስ፣ ትኽክለኛ መልሲ፣ መብርሂን ምንጪን ኣንብብ።',
      emptyTitle: 'ገና ጌጋታት የለን',
      emptyBody: 'ሕቶ ልምምድ ጌጋ ምስ መለስካ፣ ኣብዚ ብህድኣት ንምምርማር ይርአ።',
      savedForReview: 'ንምምርማር ተቐሚጡ',
      wrongAnswersTemplate: 'ዘይትኽክለኛ መልስታት፦ {count}',
      latestWrongAnswer: 'ዝቐረበ ዘይትኽክለኛ መልሲ',
      reviewQuestion: 'እዚ ሕቶ መርምር',
      clearReviewed: 'ምስ ተረዳእካ ኣልግስ',
    },
    dashboard: {
      eyebrow: 'ምዕባለ',
      title: 'ምዕባለኻ',
      subtitle: 'እንታይ ከም ዝተዛዘመን ኣየኖት ርእስታት ክትመርምሮም ከም ዝጠቕምን ርአ።',
      completedQuestions: 'ዝተዛዘሙ ሕቶታት',
      correctAnswers: 'ትኽክለኛ መልስታት',
      currentStreak: 'ተኸታታሊ መዓልታት ልምምድ',
      reviewQueue: 'ንምምርማር ዘድልዩ ሕቶታት',
      sparseDataNote: 'እዚ ጽማቝ ብዙሕ ምስ መለስካ ዝያዳ ይጠቅም። ከም ናይ መንግስቲ ግምገማ ኣይትውሰዶ።',
    },
    learning: {
      title: 'መንገዲ ምምሃር',
      subtitle: 'ብርእሲ ተኸታተል፣ ሓጺር መብርሂ ኣንብብ፣ ምንጪ ዘለዎም ሕቶታት ተለማመድ።',
      chapterCardQuestionCountTemplate: '{count} ሕቶታት',
      chapterProgressTemplate: '{completed} ካብ {total} ተዛዚሙ',
      startChapter: 'እዚ ክፍሊ ጀምር',
      reviewChapter: 'እዚ ክፍሊ መርምር',
      continueLearning: 'ምምሃር ቀጽል',
      lockedReleaseNote: 'እዚ ቋንቋ ገና ይዳሎ ኣሎ። ኵሉ ምርመራ ክሳብ ዝዛዘም ኣይክፈትን።',
    },
  },
  complianceAndMonetization: {
    complianceLinks: {
      title: 'ሕጋዊ ሓበሬታን ምንጭታትን',
      openLabelTemplate: 'ክፈት፦ {label}',
      links: {
        aboutTheTest: 'ብዛዕባ ፈተና',
        disclaimer: 'መብርሂ ሓላፍነት',
        privacy: 'ምስጢርነት',
        terms: 'ቅድመ-ኩነታት',
        sources: 'ምንጭታት ምምሃር',
        support: 'ደገፍ',
      },
    },
    legalPage: {
      defaultBackLabel: '← ናብ ፕሮፋይል ተመለስ',
      defaultBackAccessibilityLabel: 'ናብ ፕሮፋይል ተመለስ',
      externalLinkAccessibilityTemplate: 'ናይ ደገ ገጽ ክፈት፦ {label}',
    },
    privacy: {
      title: 'ፖሊሲ ምስጢርነት',
      noAccountRequired: {
        title: 'ኣካውንት ኣየድልን',
        body: 'እዚ መተግበሪ ኣካውንት፣ ኢመይል፣ ተሌፎን ወይ ፕሮፋይል ኣይሓትትን። ብዘይ ምዝገባ ክፍልታት ምምሃር ክትጥቀም ትኽእል።',
      },
      localProgressStorage: {
        title: 'ምዕባለኻ ኣብዚ መሳርሒ ጥራይ ይቕመጥ',
        body: 'ምዕባለ፣ ቅጥዕታት፣ ዝተሓዝኡ ሕቶታት፣ ዘይትኽክለኛ መልስታት፣ XP፣ ተኸታታሊ መዓልታት ልምምድን ምርጫ ድምጽን ኣብዚ መሳርሒ ይቕመጡ።',
      },
      adsAndPurchases: {
        title: 'ምልክታታትን ዕድጊታትን',
        body: 'ናይ ነጻ ስሪት ኣብ ገጻት ምምሃር ምልክታታት ከርኢ ይኽእል። ናይ ግዜ ፈተና ልምምድ ገጻት ምልክታታት የብሎምን። ምልክታታት ምእላይ ሓደ ግዜ ዝኽፈል ዕድጊ እዩ፣ ካብ ድኳን መተግበሪ ክምለስ ይኽእል።',
      },
      dataBoundary: {
        title: 'ስሱዕ ሓበሬታ ኣይትስደድ',
        body: 'ኣብ መልእኽቲ ደገፍ ስምካ፣ መንነት ቁጽሪ፣ ዝርዝር ጉዳይ ስደት ወይ ናይ መንግስቲ ሰነድ ኣይትስደድ። መተግበሪ ንምምሃርካ ነዚ ሓበሬታ ኣየድልዮን።',
      },
    },
    monetization: {
      removeAdsTitle: 'ምልክታታት ኣልግስ',
      removeAdsActiveTitle: 'ብዘይ ምልክታታት ምምሃር ተኸፊቱ ኣሎ',
      removeAdsBodyTemplate:
        'ናይ ነጻ ገጻት ምምሃር ምልክታታት ክህልዎም ይኽእል። {price} ሓደ ግዜ ብምኽፋል ምልክታታት ካብ ገጻት ምምሃር ይእለዩ፤ ፈተና ልምምድ ምልክታታት የብሉን።',
      pricingPitchTemplate: '{price} ሓደ ግዜ ምኽፋል ምልክታታት የልግስ። ወርሓዊ ምዝገባ ኣይኮነን።',
      buyLabelTemplate: 'ብ {price} ዓድግ',
      restoreLabel: 'ዝሓለፈ ዕድጊ መልስ',
      statusMessages: {
        idle: 'ቀደም ዓዲግካ እንተኾንካ፣ ኣብዚ ክትመልሶ ትኽእል።',
        pending: 'ካብ ድኳን መተግበሪ ምርግጋጽ ንጽበ ኣሎና።',
        purchased: 'ምልክታታት ኣብዚ መሳርሒ ተዓጽዮም።',
        restored: 'ዕድጊ ተመሊሱ፣ ምልክታታት ድማ ተዓጽዮም።',
        error: 'ዕድጊ ኣብዚ ግዜ ኣይርከብን። ድሒርካ እንደገና ፈትን።',
      },
    },
  },
  remainingHighFrequencyRoutes: {
    onboarding: {
      eyebrow: 'እንቋዕ ብደሓን መጻእካ',
      title: 'ብዛዕባ ሕብረተሰብ ኣብ ሽወደን ብህድኣት ተዳሎ',
      subtitle: 'ናጻ መሳርሒ ምምሃር፦ መዓልታዊ ልምምድ፣ ፈተና ልምምድን ምምርማር ዘይትኽክለኛ መልስታትን።',
      chooseLanguage: 'ቋንቋ ሕቶታት ምረጽ',
      setGoal: 'ዕላማ መዓልታዊ ኣቐምጥ',
      startLearning: 'ምምሃር ጀምር',
      privacyNote: 'ምዕባለ ምምሃር ኣብዚ መሳርሒ ጥራይ ይቕመጥ። ኣካውንት ኣየድልን።',
    },
    aboutTheTest: {
      eyebrow: 'ብዛዕባ ፈተና',
      title: 'እዚ መተግበሪ እንታይ ክትለማመድ ይሕግዘካ',
      body: 'እዚ መተግበሪ ደሞክራሲ፣ መሰላት፣ ግዴታታትን ትካላት ኣብ ሽወደንን ንምምርማር ይሕግዘካ። ከም ፓርላማ ሽወደን (Riksdag) ዝኣመሰሉ ስማት ትካላት ሽወደን ይዕቅብ።',
      independenceTitle: 'ናይ መንግስቲ ፈተና ኣይኮነን',
      independenceBody:
        'እዚ መተግበሪ ናጻ መሳርሒ ምምሃር እዩ። UHR፣ Migrationsverket ወይ ካልእ መንግስታዊ ትካል ኣይውክልን፣ ናይ መንግስቲ ውሳነ ድማ ኣይተስፉን።',
      sourceBoundary:
        'ጽሑፋት ምምሃር ኣብ መወከሲ ጽሑፍ UHR ተመርኲሶም ተዳልዮም፣ ብሓፈሻዊ ሓበሬታ ድማ ይድገፉ። እዋናዊ ሓበሬታ ወትሩ ካብ ዝምልከቶ ትካል ፈትሽ።',
    },
    support: {
      title: 'ደገፍን ርእይቶን',
      subtitle: 'ጽሑፍ ግልጺ እንተዘይኮይኑ፣ ምንጪ ምርመራ እንተድልዩ፣ ወይ ገለ ነገር እንተዘይሰሪሑ ጻሕፈልና።',
      feedbackPrompt: 'ጸገም ወይ ሓሳብ ግለጽ',
      privacyReminder: 'ውልቃዊ ሓበሬታ ወይ ሰነድ ኣይትስደድ። ገጽ፣ ሕቶ ወይ ክፋል ጽሑፍ ምግላጽ ይኣክል።',
      sendFeedback: 'ርእይቶ ስደድ',
    },
    sources: {
      title: 'ምንጭታት ምምሃር',
      subtitle:
        'ሕቶ ወይ መብርሂ ኣብ ኣየናይ ጽሑፍ ከም ዝተመርኰሰ ፈትሽ። ምንጪ ምጥቃስ እዚ መተግበሪ ብዚ ትካል ከም ዝተፈቐደ ማለት ኣይኮነን።',
      uhrLabel: 'መወከሲ ጽሑፍ UHR',
      publicInfoLabel: 'ሓፈሻዊ ሓበሬታ ካብ መንግስታዊ ትካላት',
      openSource: 'ምንጪ ክፈት',
    },
    search: {
      title: 'ሓሳባትን ክፍልታትን ድለ',
      placeholder: 'ርእሲ፣ ትካል ወይ ቁልፊ ቃል ጻሕፍ',
      emptyTitle: 'ውጽኢት የለን',
      emptyBody: 'ሓጺር ቃል ፈትን፣ ንኣብነት “Riksdag”، “ኮሙን” ወይ “መሰላት”。',
      resultTypeLabels: {
        chapter: 'ክፍሊ',
        question: 'ሕቶ',
        glossary: 'ሓሳብ',
      },
    },
  },
};
