/**
 * Phase-2 Simplified Chinese UI preview copy.
 *
 * This is intentionally not wired into AppLanguage or release selection yet.
 * It gives reviewers a typed, testable slice for the settings screen and the
 * language picker while zh-Hans remains unavailable in lib/i18n/locales.ts and
 * blocked in docs/localization/readiness.json.
 */
export const zhHansUiPreview = {
  locale: 'zh-Hans',
  status: 'preview_only_release_blocked',
  sourceStyleGuide: 'docs/localization/sample-corpus/zh-Hans/style-guide.md',
  sourcePhrasebook: 'locales/zh-Hans/phrasebook.md',
  settings: {
    title: '设置',
    subtitle: '管理题目语言、语音朗读、主题和每日学习目标。',
    backToProfile: '← 返回个人页',
    backToProfileAccessibilityLabel: '返回个人页',
    questionLanguageTitle: '题目语言',
    languageAccessibilityLabelTemplate: '将题目语言设为 {label}',
    languageOptions: {
      sv: '瑞典语',
      en: '英语辅助',
    },
    audioTitle: '语音朗读',
    audioEnabledLabel: '语音朗读已开启',
    audioDisabledLabel: '语音朗读已关闭',
    enableAudioAccessibilityLabel: '开启语音朗读',
    disableAudioAccessibilityLabel: '关闭语音朗读',
    themeModeTitle: '主题',
    themeSystemLabel: '跟随系统',
    themeLightLabel: '浅色',
    themeDarkLabel: '深色',
    themeModeSummaryTemplate: '当前主题：{label}',
    setThemeModeAccessibilityLabelTemplate: '选择主题：{label}',
    dailyGoalTitle: '每日目标',
    dailyGoalSummaryTemplate: '每天答 {answerCount} 题',
    dailyGoalPresetLabels: {
      5: '快速练习',
      10: '稳步练习',
      20: '集中练习',
      40: '强化练习',
    },
    setDailyGoalAccessibilityLabelTemplate: '将每日目标设为 {goal} 题',
    importTitle: '导入学习数据',
    importSectionSubtitle: '粘贴本设备导出的 JSON 学习数据。写入前会先显示摘要，方便你确认。',
    importPurchasesNote: '购买、收据和应用内购数据不会导入。购买项目请通过应用商店恢复。',
    importPasteLabel: '粘贴 JSON 导出内容',
    importPastePlaceholder: '在这里粘贴导出内容',
    importPreview: '预览导入内容',
    importPreviewAccessibilityLabel: '预览本地学习数据导入',
    importReset: '清空导入框',
    confirmImport: '确认导入',
    confirmImportAccessibilityLabel: '确认导入本地学习数据',
    importSuccess: '导入已完成。',
    importSummaryTitle: '导入前摘要',
    importSummaryTemplates: {
      completedQuestions: '{count} 道题有保存的学习进度',
      bookmarks: '{count} 个收藏题目',
      wrongAnswers: '{count} 条错题复习记录',
      mockExams: '{count} 条模拟考试记录',
      fsrsCards: '{count} 张 FSRS 复习卡片',
      fsrsDays: '{count} 天 FSRS 复习记录',
      settings: '{count} 项设置',
      streakFreeze: '连续学习天数和冻结状态包含在内',
    },
    importErrors: {
      emptyInput: '请先粘贴 JSON，再预览。',
      invalidJson: '无法读取这段 JSON。',
      invalidSchema: '导入内容格式不正确，或包含未知的顶层字段。',
      unsupportedVersion: '暂不支持这个导入版本。',
      purchaseFieldsRejected:
        '导入内容包含购买、收据或应用内购字段。请移除这些字段，并通过应用商店恢复购买项目。',
      noSupportedStudyData: '导入内容中没有可支持的学习数据。',
    },
  },

  entryPoints: {
    home: {
      eyebrow: '学习概览',
      title: '安心学习，一次掌握一个瑞典社会知识点',
      subtitle:
        '用清晰的学习路径准备瑞典社会知识：每天答题、做模拟考试、复习错题，并查看有资料依据的答案解析。',
      startPractice: '开始练习',
      startPracticeAccessibilityLabel: '开始推荐练习',
      browseChapters: '浏览章节',
      browseChaptersAccessibilityLabel: '浏览全部社会知识章节',
      studyLoopTitle: '更顺手的学习流程',
      studyLoopSubtitle: '借鉴社会知识考试和语言学习应用的做法：下一步清楚、反馈及时、进度看得见。',
      guidedPathTitle: '从基础学习到模拟练习',
      guidedPathSubtitle: '按 13 个社会知识章节分三步学习，继续上次进度，并保持每日练习。',
      guidedPathDailyTitle: '每日练习',
      guidedPathDailyCta: '开始今天的练习',
      guidedPathDailyTextTemplate: '今天已答 {completed}/{goal} 题，方便保持学习节奏。',
      guidedPathDailyAccessibilityLabelTemplate:
        '开始今天的练习。今天已完成 {completed} / {goal} 个答案。',
      guidedPathResumeCta: '继续下一章',
      guidedPathResumeAccessibilityLabelTemplate: '继续学习：{stageTitle}',
      readinessTitle: '准备度提示',
      readinessMetricLabel: '准备度',
      readinessSparseNote: '根据你目前的答题记录估算。多答几题后提示会更可靠。',
      readinessCta: '做一次模拟考试',
      readinessCtaAccessibilityLabel: '开始模拟考试，用来查看准备度提示',
      readinessDetailsTemplate: '正确率 {accuracyPercent}% · 已练习 {coveragePercent}% 的章节',
      readinessAccessibilityLabelTemplate: '准备度提示：{score}%。{verdict}。{details}',
      readinessVerdicts: {
        notReadyYet: '先多练几轮',
        gettingThere: '方向对了',
        almostReady: '接近准备好',
        strongPreparation: '准备很扎实',
      },
      feedbackTitle: '把需要复习的内容集中起来',
      feedbackText: '收藏题和错题会集中保存，配有资料依据的解析；考试模式中不显示广告。',
      feedbackLink: '复习已保存的题目',
      feedbackLinkAccessibilityLabel: '复习已收藏或答错的题目',
    },
    profile: {
      eyebrow: '本地个人页',
      title: '不注册账号也能查看进度',
      subtitle: '目标、语言模式、连续学习天数和徽章都保存在本设备上，便于你私下学习。',
      studySetupTitle: '学习设置',
      studySetupSubtitle: '小而稳定的每日目标，比临时长时间突击更容易坚持。',
      openSettings: '打开设置',
      openSettingsAccessibilityLabel: '打开设置',
      dashboardTitle: '进度概览',
      dashboardSubtitle: '学习活动、章节进度和 XP 会显示在单独页面。',
      dashboardCta: '查看概览',
      dashboardAccessibilityLabel: '打开进度概览',
      badgesTitle: '徽章',
      badgesSubtitle: '用成就提示展示进步，不打断学习。',
      badgeUnlocked: '已解锁',
      badgeLocked: '未解锁',
      levelMetric: '等级',
      dayStreakMetric: '连续学习天数',
      completedMetric: '已完成',
      questionsHelper: '题',
      languageBadge: '英语辅助',
      answersPerDay: '题/天',
    },
    practice: {
      badge: '5 分钟练习',
      questionTitleTemplate: '第 {questionNumber} 题',
      subtitle: '先作答，再查看即时反馈和 UHR 参考材料，然后继续下一题。',
      completedQuestionsTemplate: '已答题目：{count}',
      emptyTitle: '目前还没有可练习的题目。',
      bookmark: '收藏',
      bookmarked: '已收藏',
      bookmarkAccessibilityLabels: {
        add: '收藏这道题',
        remove: '取消收藏这道题',
      },
      nextQuestion: '下一题',
      nextQuestionAccessibilityLabel: '前往下一道练习题',
      tryAgain: '再试一次',
      tryAgainAccessibilityLabel: '重新尝试这道练习题',
      scoreLabel: '得分',
      supplementaryToggleOn: '包含补充题',
      supplementaryToggleOff: '只看 UHR 题目',
      provenanceUhrLabel: 'UHR 参考材料',
      provenanceSupplementaryLabel: '补充题',
      provenanceEditorialLabel: '编辑说明',
      aboutSourcesShow: '关于资料来源',
      aboutSourcesHide: '关闭资料来源说明',
      aboutSourcesUhrTitle: 'UHR 参考材料',
      aboutSourcesUhrBody:
        '这些题目直接对应 UHR 学习材料《Sverige i fokus》。模拟考试只使用 UHR 题目。',
      aboutSourcesSupplementaryTitle: '补充题',
      aboutSourcesSupplementaryBody:
        '根据 UHR 题目改写，用另一个角度练习同一知识点。只有开启补充题时才会显示。',
      aboutSourcesEditorialTitle: '编辑说明',
      aboutSourcesEditorialBody:
        '由我们补充撰写，用来解释 UHR 材料没有直接展开的背景内容。不会出现在模拟考试中。',
    },
  },

  quizFeedback: {
    answerOption: {
      fallbackLabel: '答案选项',
      selectAccessibilityLabelTemplate: '选择答案：{label}',
      stateLabels: {
        selected: '已选择',
        correct: '正确答案',
        incorrect: '答错的选项',
      },
    },
    explanationPanel: {
      title: '答案解析',
      fallback: '这道题暂时没有答案解析。',
      accessibilityLabelPrefix: '答案解析',
    },
    sourceCitation: {
      label: '资料来源',
      pagePrefix: '第 {pageApprox} 页',
      unavailable: '暂无资料来源',
      uhrReferenceLabel: 'UHR 参考材料',
      defaultSourceTitle: 'Sverige i fokus',
      basedOnUhrTemplate: '依据 UHR 参考材料整理：{chapter}，{section}。',
    },
    confidenceRating: {
      title: '你有多确定？',
      subtitle: '可选的 Pro 校准工具，用来帮助你了解自己对答案的把握。',
      groupLabel: '可选的答案把握程度评分',
      optionLabelTemplate: '将把握程度设为 5 分中的 {value} 分：{label}',
      options: {
        1: '猜的',
        2: '不太确定',
        3: '有点把握',
        4: '比较确定',
        5: '很确定',
      },
    },
    resultFeedback: {
      correct: '答对了。',
      incorrect: '这次选错了。',
      correctAnswerLabel: '正确答案',
      yourAnswerLabel: '你的答案',
      reviewExplanation: '查看解析',
      keepGoing: '继续加油',
      mistakeReassurance: '错一次没关系，把这个知识点记牢就好。',
    },
  },

  mockExamAndMistakes: {
    mockExamConfig: {
      title: '设置模拟考试',
      subtitle: '选择题目数量、练习时长和章节范围。提交前不会显示答案反馈。',
      startLabel: '开始模拟考试',
      startAccessibilityLabel: '按当前设置开始模拟考试',
      practiceLabel: '先练习',
      resetLabel: '重置设置',
      allChaptersLabel: '全部章节',
      clearChaptersLabel: '不选章节',
      chaptersLabel: '章节',
      selectedChaptersValueTemplate: '已选 {count} 个章节',
      questionCountLabel: '题目数量',
      incrementQuestionAccessibilityLabel: '增加题目数量',
      decrementQuestionAccessibilityLabel: '减少题目数量',
      durationLabel: '练习时长',
      durationValueTemplate: '{minutes} 分钟',
      incrementDurationAccessibilityLabel: '增加练习时长',
      decrementDurationAccessibilityLabel: '减少练习时长',
      feedbackLabel: '提交前不显示反馈',
      localSaveLabel: '仅保存在本设备上',
      scoreModeLabel: '练习结果',
      sourceScopeLabel: '基于 UHR 的题目',
    },
    resultSummary: {
      resultBadgeLabel: '练习结果',
      scoreLabel: '得分',
      metricTemplate: '{correctCount}/{totalCount} 题答对',
      percentTemplate: '{percent}%',
      progressAccessibilityTemplate: '正确率 {percent}%',
      statusLabels: {
        strong: '练习表现扎实',
        review: '建议继续复习',
      },
      accessibilityLabelTemplate: '{statusLabel}。正确率 {percent}%。{metricLabel}。',
      reviewMistakesAction: '复习错题',
      tryAnotherExamAction: '再做一次模拟考试',
    },
    mistakesReview: {
      badge: '智能复习',
      title: '错题复习',
      subtitle: '把答错的题目、答案解析、资料来源和错误次数放在同一个地方复习。',
      emptyTitle: '还没有错题',
      emptyText: '练习中答错的题目会显示在这里，方便之后复习。',
      emptyPracticeLink: '开始练习',
      emptyPracticeAccessibilityLabel: '练习较难的题目',
      mistakeBadge: '再练一次',
      mistakeTitle: '需要再练的题目',
      bookmarkedBadge: '已保存',
      bookmarkedTitle: '收藏题目',
      bookmarkedMeta: '已保存，方便集中复习',
      selectedWrongAnswerLabel: '你上次选的答案',
      correctAnswerLabel: '正确答案',
      wrongAnswersTemplate: '答错次数：{count}',
      answerReviewAccessibilityTemplate:
        '需要复习的题目。你上次选的答案：{selectedWrongAnswer}。正确答案：{correctAnswer}。',
      answerReviewAccessibilityNoWrongTemplate: '需要复习的题目。正确答案：{correctAnswer}。',
    },
  },

  dashboardAndLearning: {
    dashboard: {
      eyebrow: '本地学习数据',
      title: '进度概览',
      subtitle: '查看最近的练习活动、已覆盖的章节，以及连续学习天数的变化。',
      homeLink: '返回首页',
      homeLinkAccessibilityLabel: '返回首页',
      summaryLineTemplate:
        '本周已答 {questionsAnswered} 题 · 已练习 {touchedChapters} 个章节 · {unresolvedMistakes} 个待复习错题',
      summaryAccessibilityTemplate:
        '进度概览：本周已答 {questionsAnswered} 题，已练习 {touchedChapters} 个章节，{unresolvedMistakes} 个待复习错题。',
      activity: {
        title: '活跃日期',
        subtitle: '每个方格代表一天的答题记录。',
        emptyState: '答几道题后，这里会显示你的学习活动图。',
        summaryTemplate:
          '这一段时间共答 {totalAnswers} 题，{activeDays} 天有学习记录，单日最多 {maxDayCount} 题。',
      },
      streakXp: {
        title: '连续学习和 XP',
        subtitle: '显示最近 30 天的等级和每日学习节奏。',
        emptyState: '开始答对题目后，XP 折线会显示在这里。',
        levelLabel: '等级',
        streakLabel: '连续学习天数',
        summaryTemplate:
          '最近 30 天获得 {totalXp} XP，{activeDays} 天有学习记录，连续学习 {currentStreak} 天，等级 {level}。',
      },
      chapterProgress: {
        title: '章节进度',
        subtitle: '每个章节同时显示正确率和覆盖度，方便判断下一步复习重点。',
        accuracyLabel: '正确率',
        coverageLabel: '覆盖度',
        chapterOrder: '按章节顺序',
        weakestFirst: '薄弱章节优先',
        emptyState: '答题后，这里会显示各章节的进度。',
        linkLabelTemplate: '打开章节：{chapterName}',
        sortAccessibilityLabelTemplate: '章节排序方式：{mode}',
      },
    },
    learning: {
      eyebrow: '学习路径',
      title: '按章节学习，下一步更清楚',
      subtitle: '每个章节都会显示范围和本设备上的学习进度，帮助你决定先学哪里。',
      flashcardSectionTitle: '快速抽认卡',
      flashcardSectionSubtitle: '从题库中抽出三张有资料依据的卡片。先读题、说出答案，再马上对照。',
      sectionTitle: '13 个社会知识领域',
      sectionSubtitle: '按接近资料来源的章节学习，然后用同一批内容练习。',
      chapterLink: {
        contentQueued: '内容已列入计划',
        progressTemplate: '已练习 {completedCount}/{questionCount} 题',
        accessibilityTemplate:
          '打开章节：{primaryName}。另一种名称：{secondaryName}。进度：{progressLabel}。',
      },
      chapterCard: {
        chapterUnavailable: '章节暂不可用',
        contentQueued: '内容已列入计划',
        practicedStatusTemplate: '已练习 {completedCount}/{questionCount} 题',
        accessibilityLabels: {
          chapterTemplate: '章节：{title}',
          secondaryNameTemplate: '另一种名称：{name}',
          statusTemplate: '状态：{status}',
          descriptionTemplate: '说明：{description}',
        },
      },
      chapterProgressCard: {
        answeredLabel: '已答',
        correctLabel: '答对',
        accuracyLabel: '正确率',
        progressTemplate: '完成度 {progressPercent}%',
      },
    },
  },

  complianceAndMonetization: {
    complianceLinks: {
      title: '法律信息和资料来源',
      openLabelTemplate: '打开：{label}',
      links: {
        aboutTheTest: '关于考试',
        disclaimer: '说明',
        privacy: '隐私',
        terms: '条款',
        sources: '资料来源',
        support: '支持',
      },
    },
    legalPage: {
      defaultBackLabel: '← 返回个人页',
      defaultBackAccessibilityLabel: '返回个人页',
      externalLinkAccessibilityTemplate: '打开外部网站：{label}',
    },
    privacy: {
      title: '隐私政策',
      noAccountRequired: {
        title: '无需账号',
        body: '本应用不要求注册账号、电子邮箱、电话号码或个人资料。你可以匿名使用完整学习功能。',
      },
      localProgressStorage: {
        title: '学习进度保存在本设备上',
        body: '学习进度、设置、收藏题目、错题、XP、连续学习天数和语音偏好会保存在本设备上，用来记住你的练习状态。',
      },
      gdprRights: {
        title: '你在 GDPR 下的权利',
        body: '你可以要求导出或删除通过“支持”页面发送的支持消息。本设备上的进度、设置和购买状态，可以通过卸载应用或清除应用数据删除。',
      },
      adsAndPurchases: {
        title: '广告和购买',
        body: '免费版本会在学习页面显示 Google Mobile Ads 广告。计时模拟考试页面不显示广告。移除广告是一次性非消耗型购买，价格为 29 瑞典克朗，可通过应用商店恢复。',
      },
      adConsent: {
        title: '广告同意',
        body: '在 iOS 上，基于跟踪的广告会先请求 App Tracking Transparency 授权。需要时，会先显示 Google UMP 同意表单，再显示真实 AdMob 广告。',
      },
      providerProcessing: {
        title: '服务提供方的数据处理',
        body: 'Google Mobile Ads 和应用商店可能处理设备、广告、同意和购买状态信息，用于展示广告、应用移除广告权益和恢复购买。本应用不收集公民身份状态、移民案件细节、政府证件号或注册个人资料。',
      },
    },
    monetization: {
      removeAdsEyebrow: '移除广告',
      removeAdsActiveEyebrow: '已启用无广告学习',
      removeAdsTitle: '移除广告',
      removeAdsActiveTitle: '无广告学习已启用',
      removeAdsBodyTemplate:
        '免费学习页面会显示 AdMob 广告。一次性支付 {price}，即可移除学习页面广告；模拟考试页面本来就不显示广告。',
      pricingProofTemplate: '{questionCount} 道练习题，覆盖 {chapterCount} 个章节',
      pricingPitchTemplate: '一次性支付 {price} 移除广告。没有订阅，计时模拟考试始终不显示广告。',
      buyLabelTemplate: '购买 {price}',
      buyAccessibilityLabelTemplate: '以 {price} 购买“移除广告”',
      buyAccessibilityHint: '应用商店确认后，学习页面广告会被移除。考试模式本来就不显示广告。',
      restoreLabel: '恢复购买',
      restoreAccessibilityLabel: '恢复“移除广告”购买',
      restoreAccessibilityHint: '检查同一个应用商店账号是否已经购买过“移除广告”。',
      buying: '正在购买…',
      restoring: '正在恢复…',
      placementTitleTemplate: '移除 {placementLabel} 附近的广告',
      placementBody:
        '应用商店确认后，这个广告位和其他学习页面广告都会隐藏。计时模拟考试已经不显示广告。',
      statusAccessibilityTemplate: '移除广告状态：{message}',
      statusMessages: {
        idle: '一次性购买。如果你已经买过，可以恢复购买。',
        error: '当前无法购买。请稍后再试。',
        notFound: '没有找到之前的“移除广告”购买记录。',
        pending: '正在等待应用商店确认，然后再移除广告。',
        persistenceFailed: '购买已确认，但本设备未能保存无广告状态。请尝试恢复购买。',
        purchased: '本设备上的广告已关闭。',
        restored: '购买已恢复，本设备上的广告已关闭。',
      },
    },
  },

  remainingHighFrequencyRoutes: {
    onboarding: {
      eyebrow: '欢迎',
      title: '轻松准备瑞典社会知识考试',
      subtitle: '一个独立的小学习助手，用来每天练习、做模拟考试、复习错题。',
      steps: [
        '学习瑞典社会知识概念，需要时可参考英语辅助。',
        '用带 UHR 参考信息的问题和解析练习。',
        '无需账号，进度只保存在本设备上。',
      ],
      dailyGoalTitle: '选择一个容易坚持的每日目标',
      dailyGoalSubtitle: '先从容易保持的节奏开始。以后可以随时修改。',
      dailyGoalPresets: {
        10: {
          label: '轻松',
          summary: '每天 10 题',
          helper: '适合刚开始、想低压力建立习惯的时候。',
          accessibilityLabel: '选择轻松每日目标：10 题',
        },
        20: {
          label: '稳定',
          summary: '每天 20 题',
          helper: '适合多数日子都能保持的学习节奏。',
          accessibilityLabel: '选择稳定每日目标：20 题',
        },
        40: {
          label: '加强',
          summary: '每天 40 题',
          helper: '适合临近模拟考试、想多练一轮的时候。',
          accessibilityLabel: '选择加强每日目标：40 题',
        },
      },
      startStudying: '开始学习',
      startStudyingAccessibilityLabel: '开始学习',
      adjustSettings: '调整设置',
      adjustSettingsAccessibilityLabel: '打开设置',
      decideLater: '稍后再决定',
      decideLaterAccessibilityLabel: '不选择每日目标，继续使用应用',
    },
    aboutTheTest: {
      eyebrow: '关于考试',
      title: '瑞典公民身份社会知识考试是什么？',
      subtitle:
        'UHR 介绍的第一场考试考查瑞典社会基础知识，计划于 2026 年 8 月 15 日在斯德哥尔摩举行。',
      sections: {
        what: {
          title: '这是什么考试？',
          body: '公民身份考试是由 UHR 负责的知识考试。第一部分是社会知识。瑞典语考试会在之后推出。',
        },
        who: {
          title: '谁需要参加？',
          body: '瑞典移民局决定谁可以参加考试。只有收到瑞典移民局来信后才能报名；知识要求也可能用参加考试以外的方式满足。',
        },
        format: {
          title: '第一场考试目前已知什么？',
          body: 'UHR 已确认第一场考试日期为 2026 年 8 月 15 日，地点在斯德哥尔摩。具体时间、地点、调整安排和实务准备信息会稍后公布。',
        },
        material: {
          title: '本应用依据什么材料？',
          body: '本应用的 UHR 模式依据学习材料《Sverige i fokus》。我们的练习题不是 UHR 考题；UHR 说明，其他机构或个人制作的网上练习题没有经过 UHR 质量审核。',
        },
        independence: {
          title: '这是官方机构出品吗？',
          body: '不是。本应用是独立学习工具，不代表 UHR、瑞典国家教育署或瑞典移民局。这里的问题不是真实考试题。',
        },
      },
      openPractice: '开始练习',
      openPracticeAccessibilityLabel: '打开练习模式',
      backHome: '返回首页',
      backHomeAccessibilityLabel: '返回首页',
    },
    support: {
      title: '支持和反馈',
      whatToReportTitle: '可以反馈什么',
      whatToReportBody:
        '如果发现内容错误、瑞典语表述不清、资料来源链接失效、语音问题或学习流程错误，可以发送支持消息。',
      noPersonalDataTitle: '不要包含个人数据',
      noPersonalDataBody:
        '请不要在支持消息中写入姓名、个人身份号码、案件编号、移民案件细节或其他敏感私人信息。',
      independentStudyToolTitle: '独立学习工具',
      independentStudyToolBody:
        '支持可以帮助处理应用功能和内容修正，但不能提供官方考试答案、移民建议或官方机构决定。',
      publicSupportPageTitle: '公开支持页面',
      openSupportPageAccessibilityLabel: '打开公开支持页面',
      questionReportContextTitle: '问题反馈上下文',
      questionReportContextBody: '发送反馈时可以使用这些上下文。它只包含应用中的题目信息。',
      noPersonalDataWarning: '不要在反馈中加入姓名、个人身份号码、案件编号或其他个人数据。',
      labels: {
        questionId: '题目 ID',
        source: '资料来源',
        activeLanguage: '当前语言',
        screen: '页面',
        selectedAnswer: '已选答案',
        missingValue: '暂无',
      },
    },
    sources: {
      title: '资料来源',
      primaryStudyMaterialTitle: '主要学习材料',
      primaryStudyMaterialBody:
        'Sverige i fokus。公民身份考试学习材料。瑞典社会基础知识。第一版。UHR 学习材料：',
      questionReferencesTitle: '题目参考信息',
      questionReferencesBody:
        '每道练习题都会显示一行资料来源，包含 UHR 章节、小节和大致页码。资料来源与题干分开显示，方便你回到学习材料核对。',
      authorityBoundariesTitle: '与官方机构的界限',
      authorityBoundariesBody:
        'UHR 的考试说明页写明，UHR 制作了学习材料；网上练习题可能由其他个人或公司制作，UHR 不为其背书，也没有经过 UHR 或其他官方机构的质量审核。本应用保持同样界限：这里是独立练习内容。',
      openEducationMaterialAccessibilityLabel: '打开 UHR 学习材料',
      openAuthorityBoundarySourceAccessibilityLabel: '打开 UHR 关于公民身份考试的页面',
    },
    search: {
      eyebrow: '可搜索参考',
      title: '搜索术语、章节和解释',
      subtitle: '用于查找关键社会知识词语的简明词表，提供瑞典语和英语解释。',
      sectionTitle: '社会知识术语',
      sectionSubtitle: '查找核心词语，并打开题库中使用这个词的章节。',
      searchLabel: '搜索术语',
      searchPlaceholder: '搜索民主、市镇、福利……',
      searchInputAccessibilityLabel: '搜索社会知识术语',
      searchCardAccessibilityLabel: '搜索社会知识术语和章节关联',
      clearSearch: '清空搜索',
      clearSearchAccessibilityLabel: '清空搜索框',
      allTermsSummaryTemplate: '共有 {count} 个社会知识参考术语',
      filteredSummaryTemplate: '显示 {visibleCount}/{totalCount} 个社会知识参考术语',
      emptyTitle: '没有匹配的术语',
      emptyBody: '可以换一个词、官方机构名称或章节名再试。',
      openChapterAccessibilityLabelTemplate: '打开章节：{chapterName}',
      termAccessibilityTemplate: '{primaryTerm}。{explanation}。关联章节：{chapterName}。',
      browseChapters: '浏览章节',
      browseChaptersAccessibilityLabel: '前往全部章节',
    },
  },
  languagePicker: {
    triggerLabelTemplate: '当前语言为 {currentLabel}。打开语言选择器。',
    closeLabel: '关闭语言选择器',
    menuLabel: '语言选择器',
    title: '选择语言',
    subtitle: '界面翻译会分批加入。每种语言在完成人工审校前，题目内容仍使用瑞典语或英语。',
    unavailableSuffix: '，正在准备',
    comingSoon: '此语言版本正在准备中。',
  },
} as const;
