/**
 * Phase-2 Traditional Chinese UI preview copy.
 *
 * This is not wired into AppLanguage or release selection. It gives reviewers a
 * typed, testable first Traditional Chinese app-UI slice while `zh-Hant` remains
 * unavailable in lib/i18n/locales.ts and blocked in docs/localization/readiness.json.
 */
export const zhHantUiPreview = {
  locale: 'zh-Hant',
  status: 'preview_only_release_blocked',
  sourceStyleGuide: 'docs/localization/sample-corpus/zh-Hant/style-guide.md',
  sourcePhrasebook: 'locales/zh-Hant/phrasebook.md',
  settings: {
    title: '設定',
    subtitle: '管理題目語言、音效、外觀與每日目標。',
    backToProfile: '← 返回個人頁面',
    backToProfileAccessibilityLabel: '返回個人頁面',
    questionLanguageTitle: '題目語言',
    languageAccessibilityLabelTemplate: '將題目語言改為：{label}',
    languageOptions: {
      sv: '瑞典文',
      en: '英文輔助',
    },
    audioTitle: '音效',
    audioEnabledLabel: '音效已開啟',
    audioDisabledLabel: '音效已關閉',
    enableAudioAccessibilityLabel: '開啟音效',
    disableAudioAccessibilityLabel: '關閉音效',
    themeModeTitle: '外觀',
    themeSystemLabel: '依照裝置設定',
    themeLightLabel: '淺色',
    themeDarkLabel: '深色',
    themeModeSummaryTemplate: '目前外觀：{label}',
    setThemeModeAccessibilityLabelTemplate: '選擇外觀：{label}',
    dailyGoalTitle: '每日目標',
    dailyGoalSummaryTemplate: '每天 {answerCount} 題',
    dailyGoalPresetLabels: {
      5: '輕鬆',
      10: '穩定',
      20: '加強',
      40: '大量',
    },
    setDailyGoalAccessibilityLabelTemplate: '設定每日目標：{goal} 題',
    importTitle: '匯入學習資料',
    importSectionSubtitle: '貼上從這個 App 匯出的 JSON。寫入任何內容前，會先顯示摘要供你確認。',
    importPurchasesNote:
      '購買紀錄、收據與 App Store 資料不會匯入。請從 App Store 或應用程式商店還原購買項目。',
    importPasteLabel: '貼上 JSON 匯出資料',
    importPastePlaceholder: '在這裡貼上匯出資料',
    importPreview: '檢查匯入內容',
    importPreviewAccessibilityLabel: '檢查這台裝置上的學習資料匯入內容',
    importReset: '清除匯入欄位',
    confirmImport: '確認匯入',
    confirmImportAccessibilityLabel: '確認匯入這台裝置上的學習資料',
    importSuccess: '匯入完成。',
    importSummaryTitle: '匯入前摘要',
    importSummaryTemplates: {
      completedQuestions: '{count} 題有已儲存進度',
      bookmarks: '{count} 題已標記複習',
      wrongAnswers: '{count} 筆錯題紀錄',
      mockExams: '{count} 筆模擬測驗紀錄',
      fsrsCards: '{count} 張 FSRS 複習卡',
      fsrsDays: '{count} 天 FSRS 複習紀錄',
      settings: '{count} 個設定',
      streakFreeze: '包含連續學習天數與保護紀錄',
    },
    importErrors: {
      emptyInput: '請先貼上 JSON，再檢查匯入內容。',
      invalidJson: '無法讀取這份 JSON。',
      invalidSchema: '匯入資料格式不正確，或含有未知欄位。',
      unsupportedVersion: '目前不支援這個匯入版本。',
      purchaseFieldsRejected:
        '匯入資料含有購買、收據或應用程式商店欄位。請移除這些欄位，並從商店還原購買項目。',
      noSupportedStudyData: '匯入資料未包含可支援的學習資料。',
    },
  },
  languagePicker: {
    title: '選擇題目語言',
    currentLanguageLabelTemplate: '目前語言：{label}',
    availableBadge: '可使用',
    unavailableBadge: '準備中',
    comingSoonTitle: '此語言版本仍在準備中。',
    comingSoonBody: '繁體中文文字仍在審閱中。完成前，App 仍以瑞典文與英文提供。',
    blockedAccessibilityLabelTemplate: '{label}：語言版本準備中',
  },
  studyEntryPoints: {
    home: {
      eyebrow: '學習計畫',
      title: '一步一步學習在瑞典的社會知識',
      subtitle: '每日練習、模擬測驗、錯題複習，以及依據 UHR 參考資料整理的簡短解析。',
      startPractice: '開始練習',
      startPracticeAccessibilityLabel: '開始建議的練習',
      browseChapters: '瀏覽章節',
      browseChaptersAccessibilityLabel: '瀏覽所有章節',
      dailyPracticeTitle: '每日練習',
      dailyPracticeTextTemplate: '今天已回答 {completed} / {goal} 題。',
      readinessTitle: '準備度提示',
      readinessSparseNote:
        '這只是依照目前答題紀錄提供的學習輔助。回答更多題後，提示會更有參考價值。',
      feedbackTitle: '留下需要複習的內容',
      feedbackText: '已標記題目與錯題會集中在同一處，並附上解析與資料來源。',
    },
    practice: {
      badge: '5 分鐘練習',
      questionTitleTemplate: '第 {questionNumber} 題',
      subtitle: '作答後查看回饋，再閱讀 UHR 參考資料中的相關內容。',
      completedQuestionsTemplate: '已完成題數：{count}',
      emptyTitle: '目前還沒有練習題。',
      nextQuestion: '下一題',
      nextQuestionAccessibilityLabel: '前往下一題練習題',
      tryAgain: '再試一次',
      tryAgainAccessibilityLabel: '再次作答這題練習題',
      bookmark: '標記複習',
      bookmarked: '已標記複習',
      bookmarkAccessibilityLabels: {
        add: '將這題標記為複習',
        remove: '移除這題的複習標記',
      },
      sourceDetailsShow: '關於資料來源',
      sourceDetailsHide: '隱藏資料來源細節',
      uhrSourceLabel: 'UHR 資料來源',
    },
    feedback: {
      correct: '答對了。',
      incorrect: '這次選錯了。',
      correctAnswerLabel: '正確答案',
      yourAnswerLabel: '你的答案',
      explanationTitle: '答案解析',
      sourceCitationLabel: '參考資料',
      encouragement: '錯一次沒關係，把這個觀念記起來就好。',
    },
    mockExam: {
      title: '模擬測驗',
      subtitle: '用有時間限制的方式練習，看看哪些主題還需要複習。這不是官方考試。',
      setupTitle: '準備模擬測驗',
      start: '開始模擬測驗',
      startAccessibilityLabel: '開始學習用的模擬測驗',
      questionProgressTemplate: '第 {current} 題，共 {total} 題',
      timeRemainingTemplate: '剩餘時間：{minutes} 分鐘',
      submit: '完成並查看結果',
      resultTitle: '模擬測驗結果',
      resultSummaryTemplate: '{total} 題中答對 {correct} 題',
      reviewAnswers: '查看答案與解析',
      localPracticeNote: '這個結果只協助你在 App 內學習，不預測官方結果。',
    },
    mistakes: {
      title: '複習錯題',
      subtitle: '回到先前選錯的題目，查看正確答案、解析與資料來源。',
      emptyTitle: '目前還沒有錯題',
      emptyBody: '練習題選錯後，會出現在這裡，方便你慢慢複習。',
      savedForReview: '已儲存供複習',
      wrongAnswersTemplate: '錯題數：{count}',
      latestWrongAnswer: '最近一次錯題',
      reviewQuestion: '複習這題',
      clearReviewed: '理解後移除',
    },
    dashboard: {
      eyebrow: '進度',
      title: '你的進度',
      subtitle: '查看已完成的內容，以及值得回頭複習的主題。',
      completedQuestions: '已完成題目',
      correctAnswers: '答對題目',
      currentStreak: '連續學習天數',
      reviewQueue: '待複習題目',
      sparseDataNote: '回答更多題後，這個摘要會更有幫助。請不要把它視為官方評量。',
    },
    learning: {
      title: '學習路徑',
      subtitle: '依主題學習、閱讀簡短解析，並用附資料來源的題目練習。',
      chapterCardQuestionCountTemplate: '{count} 題',
      chapterProgressTemplate: '已完成 {completed} / {total}',
      startChapter: '開始本章',
      reviewChapter: '複習本章',
      continueLearning: '繼續學習',
      lockedReleaseNote: '這個語言版本仍在準備中。所有審查完成前，不會開放使用。',
    },
  },
  complianceAndMonetization: {
    complianceLinks: {
      title: '法律資訊與資料來源',
      openLabelTemplate: '開啟：{label}',
      links: {
        aboutTheTest: '關於測驗',
        disclaimer: '聲明',
        privacy: '隱私權',
        terms: '條款',
        sources: '學習資料來源',
        support: '支援',
      },
    },
    legalPage: {
      defaultBackLabel: '← 返回個人頁面',
      defaultBackAccessibilityLabel: '返回個人頁面',
      externalLinkAccessibilityTemplate: '開啟外部頁面：{label}',
    },
    privacy: {
      title: '隱私權政策',
      noAccountRequired: {
        title: '不需要帳號',
        body: '這個 App 不要求帳號、電子郵件、電話或個人檔案。你可以不註冊就使用學習功能。',
      },
      localProgressStorage: {
        title: '學習進度只會儲存在這台裝置上',
        body: '進度、設定、標記題目、錯題、XP、連續學習天數與音效選擇會儲存在這台裝置上，方便 App 記住你的學習位置。',
      },
      adsAndPurchases: {
        title: '廣告與購買',
        body: '免費版本可能會在學習頁面顯示廣告。有時間限制的模擬測驗頁面不顯示廣告。移除廣告是一次性購買，可透過應用程式商店還原。',
      },
      dataBoundary: {
        title: '請不要傳送敏感資料',
        body: '向支援團隊留言時，請不要提供姓名、個人識別號碼、移民案件細節或政府文件。App 不需要這些資料也能協助你學習。',
      },
    },
    monetization: {
      removeAdsTitle: '移除廣告',
      removeAdsActiveTitle: '無廣告學習已啟用',
      removeAdsBodyTemplate:
        '免費學習頁面可能會顯示廣告。一次付款 {price} 可移除學習頁面的廣告；模擬測驗本來就不顯示廣告。',
      pricingPitchTemplate: '一次付款 {price} 即可移除廣告。這不是月費訂閱。',
      buyLabelTemplate: '以 {price} 購買',
      restoreLabel: '還原先前購買',
      statusMessages: {
        idle: '如果先前已購買，可以在這裡還原。',
        pending: '正在等待應用程式商店確認。',
        purchased: '這台裝置上的廣告已關閉。',
        restored: '購買項目已還原，廣告已關閉。',
        error: '目前無法購買。請稍後再試。',
      },
    },
  },
  remainingHighFrequencyRoutes: {
    onboarding: {
      eyebrow: '歡迎使用',
      title: '平穩準備瑞典社會知識',
      subtitle: '獨立的學習工具：每日練習、模擬測驗與錯題複習。',
      chooseLanguage: '選擇題目語言',
      setGoal: '設定每日目標',
      startLearning: '開始學習',
      privacyNote: '學習進度只會儲存在這台裝置上。App 不需要帳號。',
    },
    aboutTheTest: {
      eyebrow: '關於測驗',
      title: '這個 App 協助你練習什麼',
      body: '這個 App 協助你複習民主、權利、義務，以及在瑞典的制度與機關。它會保留瑞典議會（Riksdag）等瑞典制度名稱，而不是套用其他國家的制度。',
      independenceTitle: '不是官方考試',
      independenceBody:
        '這個 App 是獨立的學習工具，不代表 UHR、Migrationsverket 或其他機關，也不承諾任何官方決定。',
      sourceBoundary:
        '學習內容依據 UHR 參考資料整理，並參考公開資訊。最新規定請務必向相關機關確認。',
    },
    support: {
      title: '支援與意見回饋',
      subtitle: '如果文字不清楚、資料來源需要確認，或功能無法使用，請告訴我們。',
      feedbackPrompt: '描述問題或建議',
      privacyReminder: '請不要傳送個人資料或文件。描述畫面、題目或文字片段即可。',
      sendFeedback: '送出意見回饋',
    },
    sources: {
      title: '學習資料來源',
      subtitle: '查看題目或解析根據哪些資料整理。資料來源標籤不表示這個 App 已受到機關背書。',
      uhrLabel: 'UHR 參考資料',
      publicInfoLabel: '公開機關資訊',
      openSource: '開啟資料來源',
    },
    search: {
      title: '搜尋概念與章節',
      placeholder: '輸入主題、機關或關鍵字',
      emptyTitle: '找不到結果',
      emptyBody: '試試較短的字詞，例如「Riksdag」、「市鎮」或「權利」。',
      resultTypeLabels: {
        chapter: '章節',
        question: '題目',
        glossary: '概念',
      },
    },
  },
};
