/**
 * Phase-2 Simplified Chinese UI preview copy.
 *
 * This is intentionally not wired into AppLanguage or release selection yet.
 * It gives reviewers a typed, testable slice for the settings screen and the
 * language picker while zh-Hans remains unavailable in lib/i18n/locales.ts and
 * blocked in docs/localization/readiness.json.
 */
export const zhHansUiPreview = {
  locale: 'zh-Hans',
  status: 'preview_only_release_blocked',
  sourceStyleGuide: 'docs/localization/sample-corpus/zh-Hans/style-guide.md',
  sourcePhrasebook: 'locales/zh-Hans/phrasebook.md',
  settings: {
    title: '设置',
    subtitle: '管理题目语言、语音朗读、主题和每日学习目标。',
    backToProfile: '← 返回个人页',
    backToProfileAccessibilityLabel: '返回个人页',
    questionLanguageTitle: '题目语言',
    languageAccessibilityLabelTemplate: '将题目语言设为 {label}',
    languageOptions: {
      sv: '瑞典语',
      en: '英语辅助',
    },
    audioTitle: '语音朗读',
    audioEnabledLabel: '语音朗读已开启',
    audioDisabledLabel: '语音朗读已关闭',
    enableAudioAccessibilityLabel: '开启语音朗读',
    disableAudioAccessibilityLabel: '关闭语音朗读',
    themeModeTitle: '主题',
    themeSystemLabel: '跟随系统',
    themeLightLabel: '浅色',
    themeDarkLabel: '深色',
    themeModeSummaryTemplate: '当前主题：{label}',
    setThemeModeAccessibilityLabelTemplate: '选择主题：{label}',
    dailyGoalTitle: '每日目标',
    dailyGoalSummaryTemplate: '每天答 {answerCount} 题',
    dailyGoalPresetLabels: {
      5: '快速练习',
      10: '稳步练习',
      20: '集中练习',
      40: '强化练习',
    },
    setDailyGoalAccessibilityLabelTemplate: '将每日目标设为 {goal} 题',
    importTitle: '导入学习数据',
    importSectionSubtitle:
      '粘贴本设备导出的 JSON 学习数据。写入前会先显示摘要，方便你确认。',
    importPurchasesNote: '购买、收据和应用内购数据不会导入。购买项目请通过应用商店恢复。',
    importPasteLabel: '粘贴 JSON 导出内容',
    importPastePlaceholder: '在这里粘贴导出内容',
    importPreview: '预览导入内容',
    importPreviewAccessibilityLabel: '预览本地学习数据导入',
    importReset: '清空导入框',
    confirmImport: '确认导入',
    confirmImportAccessibilityLabel: '确认导入本地学习数据',
    importSuccess: '导入已完成。',
    importSummaryTitle: '导入前摘要',
    importSummaryTemplates: {
      completedQuestions: '{count} 道题有保存的学习进度',
      bookmarks: '{count} 个收藏题目',
      wrongAnswers: '{count} 条错题复习记录',
      mockExams: '{count} 条模拟考试记录',
      fsrsCards: '{count} 张 FSRS 复习卡片',
      fsrsDays: '{count} 天 FSRS 复习记录',
      settings: '{count} 项设置',
      streakFreeze: '连续学习天数和冻结状态包含在内',
    },
    importErrors: {
      emptyInput: '请先粘贴 JSON，再预览。',
      invalidJson: '无法读取这段 JSON。',
      invalidSchema: '导入内容格式不正确，或包含未知的顶层字段。',
      unsupportedVersion: '暂不支持这个导入版本。',
      purchaseFieldsRejected:
        '导入内容包含购买、收据或应用内购字段。请移除这些字段，并通过应用商店恢复购买项目。',
      noSupportedStudyData: '导入内容中没有可支持的学习数据。',
    },
  },

  entryPoints: {
    home: {
      eyebrow: '学习概览',
      title: '安心学习，一次掌握一个瑞典社会知识点',
      subtitle:
        '用清晰的学习路径准备瑞典社会知识：每天答题、做模拟考试、复习错题，并查看有资料依据的答案解析。',
      startPractice: '开始练习',
      startPracticeAccessibilityLabel: '开始推荐练习',
      browseChapters: '浏览章节',
      browseChaptersAccessibilityLabel: '浏览全部社会知识章节',
      studyLoopTitle: '更顺手的学习流程',
      studyLoopSubtitle:
        '借鉴社会知识考试和语言学习应用的做法：下一步清楚、反馈及时、进度看得见。',
      guidedPathTitle: '从基础学习到模拟练习',
      guidedPathSubtitle: '按 13 个社会知识章节分三步学习，继续上次进度，并保持每日练习。',
      guidedPathDailyTitle: '每日练习',
      guidedPathDailyCta: '开始今天的练习',
      guidedPathDailyTextTemplate: '今天已答 {completed}/{goal} 题，方便保持学习节奏。',
      guidedPathDailyAccessibilityLabelTemplate:
        '开始今天的练习。今天已完成 {completed} / {goal} 个答案。',
      guidedPathResumeCta: '继续下一章',
      guidedPathResumeAccessibilityLabelTemplate: '继续学习：{stageTitle}',
      readinessTitle: '准备度提示',
      readinessMetricLabel: '准备度',
      readinessSparseNote: '根据你目前的答题记录估算。多答几题后提示会更可靠。',
      readinessCta: '做一次模拟考试',
      readinessCtaAccessibilityLabel: '开始模拟考试，用来查看准备度提示',
      readinessDetailsTemplate: '正确率 {accuracyPercent}% · 已练习 {coveragePercent}% 的章节',
      readinessAccessibilityLabelTemplate: '准备度提示：{score}%。{verdict}。{details}',
      readinessVerdicts: {
        notReadyYet: '先多练几轮',
        gettingThere: '方向对了',
        almostReady: '接近准备好',
        strongPreparation: '准备很扎实',
      },
      feedbackTitle: '把需要复习的内容集中起来',
      feedbackText: '收藏题和错题会集中保存，配有资料依据的解析；考试模式中不显示广告。',
      feedbackLink: '复习已保存的题目',
      feedbackLinkAccessibilityLabel: '复习已收藏或答错的题目',
    },
    profile: {
      eyebrow: '本地个人页',
      title: '不注册账号也能查看进度',
      subtitle: '目标、语言模式、连续学习天数和徽章都保存在本设备上，便于你私下学习。',
      studySetupTitle: '学习设置',
      studySetupSubtitle: '小而稳定的每日目标，比临时长时间突击更容易坚持。',
      openSettings: '打开设置',
      openSettingsAccessibilityLabel: '打开设置',
      dashboardTitle: '进度概览',
      dashboardSubtitle: '学习活动、章节进度和 XP 会显示在单独页面。',
      dashboardCta: '查看概览',
      dashboardAccessibilityLabel: '打开进度概览',
      badgesTitle: '徽章',
      badgesSubtitle: '用成就提示展示进步，不打断学习。',
      badgeUnlocked: '已解锁',
      badgeLocked: '未解锁',
      levelMetric: '等级',
      dayStreakMetric: '连续学习天数',
      completedMetric: '已完成',
      questionsHelper: '题',
      languageBadge: '英语辅助',
      answersPerDay: '题/天',
    },
    practice: {
      badge: '5 分钟练习',
      questionTitleTemplate: '第 {questionNumber} 题',
      subtitle: '先作答，再查看即时反馈和 UHR 参考材料，然后继续下一题。',
      completedQuestionsTemplate: '已答题目：{count}',
      emptyTitle: '目前还没有可练习的题目。',
      bookmark: '收藏',
      bookmarked: '已收藏',
      bookmarkAccessibilityLabels: {
        add: '收藏这道题',
        remove: '取消收藏这道题',
      },
      nextQuestion: '下一题',
      nextQuestionAccessibilityLabel: '前往下一道练习题',
      tryAgain: '再试一次',
      tryAgainAccessibilityLabel: '重新尝试这道练习题',
      scoreLabel: '得分',
      supplementaryToggleOn: '包含补充题',
      supplementaryToggleOff: '只看 UHR 题目',
      provenanceUhrLabel: 'UHR 参考材料',
      provenanceSupplementaryLabel: '补充题',
      provenanceEditorialLabel: '编辑说明',
      aboutSourcesShow: '关于资料来源',
      aboutSourcesHide: '关闭资料来源说明',
      aboutSourcesUhrTitle: 'UHR 参考材料',
      aboutSourcesUhrBody:
        '这些题目直接对应 UHR 学习材料《Sverige i fokus》。模拟考试只使用 UHR 题目。',
      aboutSourcesSupplementaryTitle: '补充题',
      aboutSourcesSupplementaryBody:
        '根据 UHR 题目改写，用另一个角度练习同一知识点。只有开启补充题时才会显示。',
      aboutSourcesEditorialTitle: '编辑说明',
      aboutSourcesEditorialBody:
        '由我们补充撰写，用来解释 UHR 材料没有直接展开的背景内容。不会出现在模拟考试中。',
    },
  },
  languagePicker: {
    triggerLabelTemplate: '当前语言为 {currentLabel}。打开语言选择器。',
    closeLabel: '关闭语言选择器',
    menuLabel: '语言选择器',
    title: '选择语言',
    subtitle:
      '界面翻译会分批加入。每种语言在完成人工审校前，题目内容仍使用瑞典语或英语。',
    unavailableSuffix: '，正在准备',
    comingSoon: '此语言版本正在准备中。',
  },
} as const;
