const assert = require('node:assert/strict');
const { execFileSync } = require('node:child_process');
const test = require('node:test');

test('full content production validates 500 published UHR-referenced questions', () => {
  const output = execFileSync(process.execPath, ['scripts/validate-content.js'], {
    encoding: 'utf8',
  });
  const match = output.match(/\{[\s\S]*\}/);
  assert.ok(match, 'validation should print JSON summary');
  const summary = JSON.parse(match[0]);
  assert.equal(summary.questions, 500);
  assert.equal(summary.publishedQuestions, 500);
  assert.equal(summary.chapterSchemasValidated, 13);
  assert.equal(summary.chapterTextFieldsNormalizedValidated, 13);
  assert.equal(summary.appConfigPluginsValidated, 5);
  assert.equal(summary.appConfigSchemaValidated, true);
  assert.equal(summary.launchAdSuppressedRoutesValidated, 6);
  assert.equal(summary.launchAdRouteSuppressionParityValidated, true);
  assert.equal(summary.releaseMonetizationPolicyFieldsValidated, 10);
  assert.equal(summary.releaseMonetizationPolicyParityValidated, true);
  assert.equal(summary.removeAdsEntitlementHookCasesValidated, 5);
  assert.equal(summary.removeAdsEntitlementHookParityValidated, true);
  assert.equal(summary.premiumEntitlementStatesValidated, 3);
  assert.equal(summary.premiumEntitlementParityValidated, true);
  assert.equal(summary.questionDisclaimerRoutesValidated, 6);
  assert.equal(summary.questionDisclaimerCopyValidated, true);
  assert.equal(summary.mockExamConfigTypeFieldsValidated, 5);
  assert.equal(summary.mockExamConfigTypeSchemaParityValidated, true);
  assert.equal(summary.mockExamConfigValidated, true);
  assert.equal(summary.mockExamRuntimeParityValidated, true);
  assert.equal(summary.mockExamChapterBalanceParityValidated, true);
  assert.equal(summary.mockExamTimerParityValidated, true);
  assert.equal(summary.examSubmissionFinalityParityValidated, true);
  assert.equal(summary.examRouteHeadersValidated, 8);
  assert.equal(summary.examRouteHeaderParityValidated, true);
  assert.equal(summary.examReviewItemsValidated, 20);
  assert.equal(summary.examReviewSourceParityValidated, true);
  assert.equal(summary.examChapterBreakdownItemsValidated, 13);
  assert.equal(summary.examChapterBreakdownParityValidated, true);
  assert.equal(summary.examGeneratorTypeAliasesValidated, 1);
  assert.equal(summary.examGeneratorTypeInterfacesValidated, 6);
  assert.equal(summary.examGeneratorTypeSchemaParityValidated, true);
  assert.equal(summary.contentTypeUnionsValidated, 3);
  assert.equal(summary.contentTypeInterfacesValidated, 5);
  assert.equal(summary.contentTypeSchemaParityValidated, true);
  assert.equal(summary.monetizationTypeUnionsValidated, 1);
  assert.equal(summary.monetizationTypeInterfacesValidated, 3);
  assert.equal(summary.monetizationTypeSchemaParityValidated, true);
  assert.equal(summary.purchaseTypeUnionsValidated, 1);
  assert.equal(summary.purchaseTypeInterfacesValidated, 7);
  assert.equal(summary.purchaseTypeSchemaParityValidated, true);
  assert.equal(summary.adConsentTypeUnionsValidated, 6);
  assert.equal(summary.adConsentTypeInterfacesValidated, 3);
  assert.equal(summary.adConsentTypeSchemaParityValidated, true);
  assert.equal(summary.mobileAdsConsentTypeInterfacesValidated, 5);
  assert.equal(summary.mobileAdsConsentTypeSchemaParityValidated, true);
  assert.equal(summary.rewardedAdTypeUnionsValidated, 1);
  assert.equal(summary.rewardedAdTypeInterfacesValidated, 3);
  assert.equal(summary.rewardedAdTypeSchemaParityValidated, true);
  assert.equal(summary.mockExamAccessTypeUnionsValidated, 1);
  assert.equal(summary.mockExamAccessTypeInterfacesValidated, 6);
  assert.equal(summary.mockExamAccessTypeSchemaParityValidated, true);
  assert.equal(summary.themeColorTokensValidated, 29);
  assert.equal(summary.themeSpaceTokensValidated, 19);
  assert.equal(summary.themeRadiusTokensValidated, 7);
  assert.equal(summary.themeTypographyTokensValidated, 22);
  assert.equal(summary.themeShadowTokensValidated, 2);
  assert.equal(summary.themeMotionTokensValidated, 7);
  assert.equal(summary.themeTokenSchemaValidated, true);
  assert.equal(summary.glossaryTermsValidated, summary.glossaryTerms);
  assert.equal(summary.uxBenchmarksValidated, 4);
  assert.equal(summary.supportedLanguagesValidated, 2);
  assert.equal(summary.localizationStringsValidated, summary.localizationStrings);
  assert.equal(summary.languageSettingsParityValidated, true);
  assert.equal(summary.settingsStoreFieldsValidated, 6);
  assert.equal(summary.settingsStoreSchemaParityValidated, true);
  assert.equal(summary.settingsDailyGoalOptionsValidated, 3);
  assert.equal(summary.settingsDailyGoalParityValidated, true);
  assert.equal(summary.settingsAudioLabelsValidated, 2);
  assert.equal(summary.settingsAudioParityValidated, true);
  assert.equal(summary.progressQuestionFieldsValidated, 8);
  assert.equal(summary.progressQuestionSchemaParityValidated, true);
  assert.equal(summary.progressTypeUnionsValidated, 2);
  assert.equal(summary.progressTypeInterfacesValidated, 4);
  assert.equal(summary.progressTypeSchemaParityValidated, true);
  assert.equal(summary.progressStoreFieldsValidated, 8);
  assert.equal(summary.progressStoreSchemaParityValidated, true);
  assert.equal(summary.badgesValidated, 4);
  assert.equal(summary.badgeMilestoneParityValidated, true);
  assert.equal(summary.practiceScoringRulesValidated, 5);
  assert.equal(summary.practiceScoringRulesParityValidated, true);
  assert.equal(summary.practiceFlowCasesValidated, 6);
  assert.equal(summary.practiceFlowParityValidated, true);
  assert.equal(summary.practiceSessionStoreFieldsValidated, 5);
  assert.equal(summary.practiceSessionStoreSchemaParityValidated, true);
  assert.equal(summary.practiceSessionStoreRuntimeParityValidated, true);
  assert.equal(summary.answerValidationTypeUnionsValidated, 1);
  assert.equal(summary.answerValidationTypeInterfacesValidated, 1);
  assert.equal(summary.answerValidationTypeSchemaParityValidated, true);
  assert.equal(summary.answerFeedbackQuestionsValidated, 500);
  assert.ok(summary.answerFeedbackOptionsValidated > summary.answerFeedbackQuestionsValidated);
  assert.equal(summary.answerFeedbackRuntimeParityValidated, true);
  assert.equal(summary.questionSpeechTextQuestionsValidated, 500);
  assert.ok(
    summary.questionSpeechTextOptionsValidated > summary.questionSpeechTextQuestionsValidated,
  );
  assert.equal(summary.questionSpeechTextParityValidated, true);
  assert.equal(summary.speechRuntimeCasesValidated, 4);
  assert.equal(summary.speechRuntimeParityValidated, true);
  assert.equal(summary.chapterQuizSessionParityValidated, 13);
  assert.equal(summary.spacedRepetitionIntervalsValidated, 5);
  assert.equal(summary.spacedRepetitionRuntimeParityValidated, true);
  assert.equal(summary.streakRulesValidated, 6);
  assert.equal(summary.streakRulesParityValidated, true);
  assert.equal(summary.xpRulesValidated, 11);
  assert.equal(summary.xpRulesParityValidated, true);
  assert.equal(summary.masteryRulesValidated, 7);
  assert.equal(summary.masteryRulesParityValidated, true);
  assert.equal(summary.sourceQuestions, 100);
  assert.equal(summary.generatedPublishedQuestions, 400);
  assert.equal(summary.authoredSourceQuestionsValidated, 100);
  assert.equal(summary.sourcePublicationParityValidated, 100);
  assert.equal(summary.generationParityValidated, true);
  assert.equal(summary.chapterGenerationParityValidated, 13);
  assert.equal(summary.generatedSourceMetadataParityValidated, 400);
  assert.equal(summary.generatedPromptTemplateParityValidated, 400);
  assert.equal(summary.generatedAnswerTemplateParityValidated, 400);
  assert.equal(summary.generatedTagTemplateParityValidated, 400);
  assert.equal(summary.questionSchemasValidated, 500);
  assert.equal(summary.publishedQuestionTypesValidated, 500);
  assert.equal(summary.questionIdSequencesValidated, 500);
  assert.equal(summary.questionBilingualTextPairsValidated, 500);
  assert.equal(summary.questionOptionBilingualTextPairsValidated, 500);
  assert.equal(summary.questionTextFieldsNormalizedValidated, 500);
  assert.equal(summary.questionAuthorityBoundaryTextValidated, 500);
  assert.equal(summary.questionPromptTextUniquenessValidated, 500);
  assert.equal(summary.questionOptionTextLabelsValidated, 500);
  assert.equal(summary.questionTypeOptionCountsValidated, 500);
  assert.equal(summary.questionOptionIdConventionsValidated, 500);
  assert.ok(summary.trueFalseQuestions > 0);
  assert.equal(summary.trueFalseOptionLabelsValidated, summary.trueFalseQuestions);
  assert.equal(summary.questionTagsValidated, 500);
  assert.equal(summary.questionBankCsvRowsValidated, 500);
  assert.equal(summary.uhrSourceMetadataValidated, true);
  assert.equal(summary.uhrMapChaptersValidated, 13);
  assert.equal(summary.uhrMapSectionsValidated, 110);
  assert.equal(summary.uhrMapTextFieldsNormalizedValidated, 140);
  assert.equal(summary.uhrMapPageRangesValidated, 13);
  assert.equal(summary.uhrSourceMaterialLinkParityValidated, true);
  assert.equal(summary.uhrSourceRetrievedDateValidated, true);
  assert.equal(summary.questionChapterReferenceParityValidated, 500);
  assert.equal(summary.uhrReferencesValidated, 500);
});
